# Generated by Django 2.1.3 on 2018-11-06 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Lastmodified',
            new_name='lastModified',
        ),
        migrations.AlterField(
            model_name='question',
            name='addedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.Question'),
        ),
    ]
