# Generated by Django 2.1.3 on 2018-11-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0002_auto_20181106_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty_description',
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('B', 'Beginner'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=50),
        ),
    ]
