# Generated by Django 2.1.3 on 2018-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0003_auto_20181106_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='archive_app.Tag'),
        ),
    ]
